name: Build VirtualAndroX APK (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with Buildozer Docker
      uses: artem-korolev/buildozer-action@v1
      with:
        buildozer-version: stable
        work-dir: ./
        buildozer-command: android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Docker
        path: bin/*.apk
        retention-days: 30
        
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        body: |
          # VirtualAndroX APK Release (Docker Build)
          
          🤖 **Android 11 Virtualization for Huawei Devices**
          
          Built with reliable Docker-based Buildozer.
          
          ## Features:
          - 🏦 Run myBSN Banking on Android 10 devices
          - 📱 Google Play Services compatibility  
          - 🔒 Secure sandboxed environment
          - ⚡ Lightweight (280MB RAM)
          
          ## Installation:
          1. Download the APK
          2. Enable "Install from unknown sources"
          3. Install and open VirtualAndroX
          4. Select "Launch myBSN Banking"
          
          **Developer:** @blackbutterfly313
