name: Build APK with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Docker
      run: |
        # Use official Buildozer Docker image with pre-configured environment
        docker run --rm \
          -v $(pwd):/src \
          -w /src \
          kivy/buildozer buildozer -v android debug
    - uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Docker
        path: bin/*.apk
