name: Build APK Nuclear Option

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: android-actions/setup-android@v2
    - run: pip install buildozer
    - run: buildozer android debug
    - uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Nuclear
        path: bin/*.apk
