name: Build VirtualAndroX APK (Simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Use older Ubuntu for compatibility
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          zlib1g-dev
          
    - name: Install Buildozer
      run: |
        pip install buildozer
        
    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Simple
        path: bin/*.apk
