name: Build APK Simple Working

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept licenses and install packages
      run: |
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-30" "build-tools;36.1.0" "platform-tools"
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Buildozer
      run: pip install buildozer cython==0.29.19
      
    - name: Build with Buildozer
      run: buildozer -v android debug
      
    - uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Simple-APK
        path: bin/*.apk
