name: Build VirtualAndroX APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.19

    - name: Build APK with Buildozer
      uses: arturoguzman/buildozer-action@v1
      with:
        buildozer-version: stable
        work-dir: ./
        target: android
        buildozer-args: -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-APK
        path: bin/*.apk
        retention-days: 7

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
