name: Build VirtualAndroX APK (Fallback)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-20.04  # Older, more stable Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-8-jdk \
          zlib1g-dev \
          python3-pip
          
    - name: Install Buildozer
      run: |
        pip install buildozer
        pip install cython==0.29.19
        
    - name: Initialize Buildozer
      run: |
        buildozer init <<< "y"
        sleep 10  # Wait for initialization
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Fallback
        path: bin/*.apk
