name: ⚡ Ultra Simple Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: ./
        buildozer-version: 1.5.0
    - uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Simple
        path: bin/*.apk
