name: Build VirtualAndroX - Simple

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.19

    - name: Create minimal buildozer.spec
      run: |
        cat > buildozer-minimal.spec << 'SPEC_EOF'
[app]
title = VirtualAndroX
package.name = virtualandrox
package.domain = org.blackbutterfly313
source.dir = .
version = 1.0.0
requirements = python3
orientation = portrait

[buildozer]
log_level = 2

[android]
api = 30
minapi = 21
ndk = 23b
sdk = 30
p4a.branch = master
android.arch = arm64-v8a
android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,ACCESS_NETWORK_STATE
android.accept_sdk_license = True

[loggers]
root = INFO
SPEC_EOF

    - name: Build with minimal requirements
      run: |
        buildozer -v android debug --profile buildozer-minimal.spec

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualAndroX-Minimal-APK
        path: bin/*.apk
